services:
  - type: web
    name: lista-presente
    env: python
    rootDir: Back-End
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    autoDeploy: true
    envVars:
      - key: APP_VERSION
        value: 3.17.1